### ISSUE TITLE
Do we want to change the LinkedList implementation I started on to an Array implementation

### ISSUE THREAD

**Issue by HerrSchreiber** [HerrSchreiber/bioinformatics#1]
If we do it will align closer with the pseudocode in the book along with Dr. Yeh's lectures. However, I did find a clever implementation with LinkedLists, and have a bit of it done already. I'm cool with either way.

**Comment by rogerogden** [comment]
I think we're good to continue using the LinkedList, Rob, since you've already invested some time in it, and you found an implementation.
